# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbody',
            name='blog_typeid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_imgurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
