# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20161118_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbody',
            options={'ordering': ['-blog_timestamp']},
        ),
    ]
