# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=200)),
                ('upper', models.IntegerField()),
                ('remark', models.TextField(null=True)),
                ('interface_sn', models.CharField(max_length=10, null=True)),
                ('interface_name', models.CharField(max_length=200, null=True)),
                ('request_method', models.CharField(max_length=20, null=True)),
                ('request_link', models.CharField(max_length=255, null=True)),
                ('response_data', models.TextField(null=True)),
                ('interface_desc', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
