# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=40, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('category_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_sn', models.CharField(blank=True, max_length=10, null=True)),
                ('interface_name', models.CharField(blank=True, max_length=200, null=True)),
                ('request_method', models.CharField(blank=True, max_length=20, null=True)),
                ('request_link', models.CharField(blank=True, max_length=255, null=True)),
                ('request_sample', models.TextField(blank=True, null=True)),
                ('response_sample', models.TextField(blank=True, null=True)),
                ('request_desc', models.TextField(blank=True, null=True)),
                ('response_desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_interface', to='testtools.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('request_param_type', models.CharField(blank=True, max_length=20, null=True)),
                ('request_param_isnull', models.IntegerField()),
                ('request_param_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_requestparam', to='testtools.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('response_param_type', models.CharField(blank=True, max_length=20, null=True)),
                ('response_param_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_responseparam', to='testtools.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='TestScenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_scenario_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_scenario_type', models.IntegerField()),
                ('interface_mapping_result', models.CharField(blank=True, max_length=200, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_interface', to='testtools.Project'),
        ),
    ]
