# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intf',
            name='interface_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intf',
            name='interface_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intf',
            name='interface_sn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='intf',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intf',
            name='request_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intf',
            name='request_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intf',
            name='response_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
