# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenarios',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_testscenarios', to='testtools.Project'),
        ),
    ]
