# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0002_testscenarios_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscenarios',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
