# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0002_auto_20161001_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='intf',
            name='context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
