# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0003_auto_20161123_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestparam',
            name='request_param_value',
            field=models.CharField(blank=True, default=b'null', max_length=255, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe5\x8f\x82\xe6\x95\xb0\xe5\x80\xbc'),
        ),
        migrations.AddField(
            model_name='testscenarios',
            name='state',
            field=models.IntegerField(default=b'0', verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe7\x9b\xae\xe5\xbd\x95\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b\xe7\x88\xb6id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='x',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\x9b\xae\xe5\xbd\x95x\xe5\x9d\x90\xe6\xa0\x87'),
        ),
        migrations.AlterField(
            model_name='category',
            name='y',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\x9b\xae\xe5\xbd\x95y\xe5\x9d\x90\xe6\xa0\x87'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interface_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe6\x8e\xa5\xe5\x8f\xa3\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interface_sn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x8e\xa5\xe5\x8f\xa3\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='request_desc',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='request_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe9\x93\xbe\xe6\x8e\xa5'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='request_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe6\x96\xb9\xe6\xb3\x95'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='request_sample',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe6\xa0\xb7\xe4\xbe\x8b'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='response_desc',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xe8\xbf\x94\xe5\x9b\x9e\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='response_sample',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xe8\xbf\x94\xe5\x9b\x9e\xe6\xa0\xb7\xe4\xbe\x8b'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='request_param_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe5\x8f\x82\xe6\x95\xb0\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='request_param_isnull',
            field=models.IntegerField(verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe5\x8f\x82\xe6\x95\xb0\xe6\x98\xaf\xe5\x90\xa6\xe5\xbf\x85\xe5\xa1\xab'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='request_param_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe5\x8f\x82\xe6\x95\xb0\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='request_param_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe5\x8f\x82\xe6\x95\xb0\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='responseparam',
            name='response_param_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe8\xbf\x94\xe5\x9b\x9e\xe5\x8f\x82\xe6\x95\xb0\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='responseparam',
            name='response_param_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe8\xbf\x94\xe5\x9b\x9e\xe5\x8f\x82\xe6\x95\xb0\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='responseparam',
            name='response_param_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xbf\x94\xe5\x9b\x9e\xe5\x8f\x82\xe6\x95\xb0\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='interface_mapping_result',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe6\x8e\xa5\xe5\x8f\xa3\xe5\xaf\xb9\xe5\xba\x94\xe7\xbb\x93\xe6\x9e\x9c'),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_testscenarios', to='testtools.Project'),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='test_scenario_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe5\x9c\xba\xe6\x99\xaf\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='test_scenario_type',
            field=models.IntegerField(verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe5\x9c\xba\xe6\x99\xaf\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='testscenarios',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
