# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0004_auto_20161002_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.IntegerField(blank=True, max_length=10, null=True)),
                ('parent_id', models.IntegerField(blank=True, max_length=10, null=True)),
                ('left', models.IntegerField(blank=True, max_length=10, null=True)),
                ('right', models.IntegerField(blank=True, max_length=10, null=True)),
                ('category_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
