# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0006_auto_20161031_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
