# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0007_auto_20161031_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='left',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='right',
            new_name='y',
        ),
    ]
