# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0008_auto_20161031_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_sn', models.CharField(blank=True, max_length=10, null=True)),
                ('interface_name', models.CharField(blank=True, max_length=200, null=True)),
                ('request_method', models.CharField(blank=True, max_length=20, null=True)),
                ('request_link', models.CharField(blank=True, max_length=255, null=True)),
                ('request_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('request_param_type', models.CharField(blank=True, max_length=20, null=True)),
                ('request_param_isnull', models.IntegerField()),
                ('request_param_desc', models.TextField(blank=True, null=True)),
                ('request_desc', models.TextField(blank=True, null=True)),
                ('response_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('response_param_type', models.CharField(blank=True, max_length=20, null=True)),
                ('response_param_desc', models.TextField(blank=True, null=True)),
                ('request_sample', models.TextField(blank=True, null=True)),
                ('response_sample', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtools.Category')),
            ],
        ),
    ]
