# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0009_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('request_param_type', models.CharField(blank=True, max_length=20, null=True)),
                ('request_param_isnull', models.IntegerField()),
                ('request_param_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interface',
            name='request_param_desc',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='request_param_isnull',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='request_param_name',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='request_param_type',
        ),
        migrations.AddField(
            model_name='requestparam',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtools.Interface'),
        ),
    ]
