# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0013_auto_20161102_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('response_param_type', models.CharField(blank=True, max_length=20, null=True)),
                ('response_param_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interface',
            name='response_param_desc',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='response_param_name',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='response_param_type',
        ),
        migrations.AlterField(
            model_name='interface',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_interface', to='testtools.Category'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_requestparam', to='testtools.Interface'),
        ),
        migrations.AddField(
            model_name='responseparam',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_responseparam', to='testtools.Interface'),
        ),
    ]
