# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0016_auto_20161103_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Intf',
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, related_name='project_interface', to='testtools.Project'),
        ),
    ]
