# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtools', '0017_auto_20161111_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_interface', to='testtools.Project'),
        ),
    ]
